@echo off
echo Cleaning the apt cache in the box...
vagrant ssh -c "sudo apt-get clean"
echo Zeroed the empty space...
vagrant ssh -c "sudo dd if=/dev/zero of=/EMPTY bs=1M"
vagrant ssh -c "sudo rm -f /EMPTY"
echo Cleaning the history...
vagrant ssh -c "cat /vagrant/tools/insecure_private_key.pub > ~/.ssh/authorized_keys"
vagrant ssh -c "cat /dev/null > ~/.bash_history && history -c"
echo Building the box...
vagrant package --output webserver.box
